/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class GiaoDienPhanMem extends javax.swing.JFrame {
    static int countFileChoose = 0;
            
    /**
     * Creates new form NewJFrame
     */
    public GiaoDienPhanMem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        thongTinNhomButton = new javax.swing.JButton();
        tieuDeLabel = new javax.swing.JLabel();
        inTTCKButton = new javax.swing.JButton();
        layThongTinTuWebsite = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        thongTinNhomButton.setText("Thông tin nhóm");
        thongTinNhomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongTinNhomButtonActionPerformed(evt);
            }
        });

        tieuDeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieuDeLabel.setText("IN THÔNG TIN CHỨNG KHOÁN");
        tieuDeLabel.setToolTipText("");
        tieuDeLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tieuDeLabel.setFocusable(false);
        tieuDeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tieuDeLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tieuDeLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        inTTCKButton.setText("In TTCK");
        inTTCKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTTCKButtonActionPerformed(evt);
            }
        });

        layThongTinTuWebsite.setText("Lấy thông tin từ Website");
        layThongTinTuWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layThongTinTuWebsiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thongTinNhomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(inTTCKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(layThongTinTuWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(tieuDeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tieuDeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thongTinNhomButton)
                    .addComponent(inTTCKButton)
                    .addComponent(layThongTinTuWebsite))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thongTinNhomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongTinNhomButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "LỖI ! Chưa có thông tin nhóm !");
        // TODO add your handling code here:
    }//GEN-LAST:event_thongTinNhomButtonActionPerformed

    private void tieuDeLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tieuDeLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tieuDeLabelAncestorAdded

    private void inTTCKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTTCKButtonActionPerformed
        BTL baitaplon = new BTL();
        try {
            baitaplon.BaiTapLon();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(GiaoDienPhanMem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(rootPane, "Đã in thông tin chứng khoán");
    }//GEN-LAST:event_inTTCKButtonActionPerformed

    private void layThongTinTuWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layThongTinTuWebsiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layThongTinTuWebsiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienPhanMem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inTTCKButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton layThongTinTuWebsite;
    private javax.swing.JButton thongTinNhomButton;
    private javax.swing.JLabel tieuDeLabel;
    // End of variables declaration//GEN-END:variables
}
