package BTL;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class GiaoDienPhanMem extends javax.swing.JFrame {
    String pathVNINDEX, pathHNXINDEX, pathUPCOMINDEX;

    /**
     * Creates new form NewJFrame
     */
    public GiaoDienPhanMem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        thongTinNhomButton = new javax.swing.JButton();
        tieuDeLabel = new javax.swing.JLabel();
        inTTCKButton = new javax.swing.JButton();
        layThongTinTuWebsite = new javax.swing.JButton();
        vnindexButton = new javax.swing.JButton();
        hnxindexButton = new javax.swing.JButton();
        upcomindexButton = new javax.swing.JButton();
        vnindexLabel = new javax.swing.JLabel();
        hnxindexLabel = new javax.swing.JLabel();
        upcomindexLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        thongTinNhomButton.setText("Thông tin nhóm");
        thongTinNhomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongTinNhomButtonActionPerformed(evt);
            }
        });

        tieuDeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieuDeLabel.setText("IN THÔNG TIN CHỨNG KHOÁN");
        tieuDeLabel.setToolTipText("");
        tieuDeLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tieuDeLabel.setFocusable(false);
        tieuDeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tieuDeLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tieuDeLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        inTTCKButton.setText("In TTCK");
        inTTCKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTTCKButtonActionPerformed(evt);
            }
        });

        layThongTinTuWebsite.setText("Lấy thông tin từ Website");
        layThongTinTuWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layThongTinTuWebsiteActionPerformed(evt);
            }
        });

        vnindexButton.setText("Chọn file VN-INDEX");
        vnindexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnindexButtonActionPerformed(evt);
            }
        });

        hnxindexButton.setText("Chọn file HNX-INDEX");
        hnxindexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hnxindexButtonActionPerformed(evt);
            }
        });

        upcomindexButton.setText("Chọn file UPCOM-INDEX");
        upcomindexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcomindexButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(thongTinNhomButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layThongTinTuWebsite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(tieuDeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 145, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(vnindexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(hnxindexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomindexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(hnxindexButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomindexButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(vnindexButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(42, 42, 42))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(inTTCKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(156, 156, 156))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(tieuDeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(thongTinNhomButton)
                                .addGap(18, 18, 18)
                                .addComponent(layThongTinTuWebsite)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(vnindexButton)
                                        .addComponent(vnindexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hnxindexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hnxindexButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomindexButton)
                                        .addComponent(upcomindexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(inTTCKButton)
                                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thongTinNhomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongTinNhomButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "LỖI ! Chưa có thông tin nhóm !");
        // TODO add your handling code here:
    }//GEN-LAST:event_thongTinNhomButtonActionPerformed

    private void tieuDeLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tieuDeLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tieuDeLabelAncestorAdded

    private void inTTCKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTTCKButtonActionPerformed
        BTL baitaplon = new BTL();
        try {
            baitaplon.BaiTapLon(pathVNINDEX,pathUPCOMINDEX,pathHNXINDEX);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(GiaoDienPhanMem.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(rootPane, "Đã in thông tin chứng khoán");
    }//GEN-LAST:event_inTTCKButtonActionPerformed

    private void layThongTinTuWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layThongTinTuWebsiteActionPerformed
//        JOptionPane.showMessageDialog(rootPane, "LỖI ! Chưa lấy được thông tin từ website !");
        // TODO add your handling code here:
        cmdCall pythonCall = new cmdCall();
        pythonCall.pythonCall();
        JOptionPane.showMessageDialog(rootPane, "Đã lấy xong thông tin trên  website ");

    }//GEN-LAST:event_layThongTinTuWebsiteActionPerformed

    private void vnindexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnindexButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("Excel", "xlsx");
        fileChooser.setFileFilter(excelFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "select file");
        if(x == JFileChooser.APPROVE_OPTION)
        {
            File f = fileChooser.getSelectedFile();
            vnindexLabel.setText(f.getAbsolutePath());
            pathVNINDEX = f.getAbsolutePath();
        }


    }//GEN-LAST:event_vnindexButtonActionPerformed

    private void hnxindexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hnxindexButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("Excel", "xlsx");
        fileChooser.setFileFilter(excelFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "select file");
        if(x == JFileChooser.APPROVE_OPTION)
        {
            File f = fileChooser.getSelectedFile();
            hnxindexLabel.setText(f.getAbsolutePath());
            pathHNXINDEX = f.getAbsolutePath();
        }
    }//GEN-LAST:event_hnxindexButtonActionPerformed

    private void upcomindexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcomindexButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("Excel", "xlsx");
        fileChooser.setFileFilter(excelFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "select file");
        if(x == JFileChooser.APPROVE_OPTION)
        {
            File f = fileChooser.getSelectedFile();
            upcomindexLabel.setText(f.getAbsolutePath());
            pathUPCOMINDEX = f.getAbsolutePath();
        }
    }//GEN-LAST:event_upcomindexButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienPhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienPhanMem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hnxindexButton;
    private javax.swing.JLabel hnxindexLabel;
    private javax.swing.JButton inTTCKButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton layThongTinTuWebsite;
    private javax.swing.JButton thongTinNhomButton;
    private javax.swing.JLabel tieuDeLabel;
    private javax.swing.JButton upcomindexButton;
    private javax.swing.JLabel upcomindexLabel;
    private javax.swing.JButton vnindexButton;
    private javax.swing.JLabel vnindexLabel;
    // End of variables declaration//GEN-END:variables
}
